#Question 1: What were the Top 10 Countries for Annual GDP Change?

In [1]:
import pandas as pd

In [40]:
df = pd.read_csv("./Data/WorldBank_GDPChange.csv")

print(df.shape)
df.head(100)

(266, 3)

                              Country_Name Country_Code  GDP_Change
0                                    Aruba          ABW   17.172509
1              Africa Eastern and Southern          AFE    4.293395
2                              Afghanistan          AFG  -20.737146
3               Africa Western and Central          AFW    3.965399
4                                   Angola          AGO    1.100000
..                                     ...          ...         ...
95                             High income          HIC    5.236045
96                    Hong Kong SAR, China          HKG    6.343106
97                                Honduras          HND   12.534096
98  Heavily indebted poor countries (HIPC)          HPC    3.864079
99                                 Croatia          HRV   13.072205

[100 rows x 3 columns]

In [27]:
df.dtypes

Country_Name     object
Country_Code     object
GDP_Change      float64
dtype: object

In [35]:
print("Q1: What were the Top 10 Countries for Annual GDP Change?")
df1 = df.sort_values(by='GDP_Change',ascending=False)
df1 = df1.iloc[0:10]
print(df1.shape)

df1

Q1: What were the Top 10 Countries for Annual GDP Change?
(10, 3)

         Country_Name Country_Code  GDP_Change
152          Maldives          MDV   41.745101
132             Libya          LBY   31.372422
149            Monaco          MCO   21.553561
94             Guyana          GUY   20.060011
146  Macao SAR, China          MAC   19.267056
0               Aruba          ABW   17.172509
185            Panama          PAN   15.335874
26             Belize          BLZ   15.226131
150           Moldova          MDA   13.944590
23       Bahamas, The          BHS   13.719735

#Question 2: What were the Bottom 15 Countries for Annual GDP Change?

In [38]:
print("Q2: What were the Bottom 15 Countries for Annual GDP Change?")
df1 = df.sort_values(by='GDP_Change',ascending=True)

df1 = df1.iloc[0:15]
print(df1.shape)
df1

Q2: What were the Bottom 15 Countries for Annual GDP Change?
(15, 3)

                    Country_Name Country_Code  GDP_Change
2                    Afghanistan          AFG  -20.737146
160                      Myanmar          MMR  -17.912945
188                        Palau          PLW  -13.333333
260                        Samoa          WSM   -7.084588
130                      Lebanon          LBN   -7.001239
76                          Fiji          FJI   -5.111607
197  Pacific island small states          PSS   -3.667728
79         Micronesia, Fed. Sts.          FSM   -3.188187
220                     Suriname          SUR   -2.729619
239                        Tonga          TON   -2.667506
44                   Congo, Rep.          COG   -2.200003
206                        Sudan          SDN   -1.868520
11                American Samoa          ASM   -1.866252
100                        Haiti          HTI   -1.798240
31             Brunei Darussalam          BRN   -1.590762

# Question 3: What was the annual GDP Change for Denmark, Spain, Mexico, Canada, United States, and the Upper Middle Income Countries?
## a. Sort this DataFrame by Annual GDP Change, Highest to Lowest

In [56]:
print("Question 3: What was the annual GDP Change for Denmark, Spain, Mexico, Canada, United States, and the Upper Middle Income Countries?")

countries = ['Denmark','Spain','Mexico','Canada','United States','Upper middle income']

df1 = df.query('Country_Name in @country')

df1 = df1.sort_values(by='GDP_Change',ascending=False)

df1 = df1.iloc[0:6]

print(df1.shape)
df1

Question 3: What was the annual GDP Change for Denmark, Spain, Mexico, Canada, United States, and the Upper Middle Income Countries?
(6, 3)

            Country_Name Country_Code  GDP_Change
249  Upper middle income          UMC    7.402123
251        United States          USA    5.945485
70                 Spain          ESP    5.519595
58               Denmark          DNK    4.855708
154               Mexico          MEX    4.720565
35                Canada          CAN    4.540887