# Lab 5: Reading Tables from an Azure SQL Database

- **Requires data files: `No file required. The database is hosted on a SQL Server running in Azure`**

- **Demonstrates and reinforces**:
    - Reading records from a database hosted on Azure.
    - SELECT, FROM, WHERE, and ORDER BY SQL operations.

<span style="color:#C1A875">NOTE: Since this database is hosted in Microsoft Azure, cold starts may result in a delay of 10-20 seconds. Please be patient as you may need to run the connection and inspector code cells multiple times for the connection to be established and the data to be retrieved.</span>

---

# Prerequisites
To begin, make sure that you have installed `sqlalchemy` and `pymssql`. You can do this by running the code cell below. This time, in addition to sqlalchemy, we also need to install `pymssql`, which is a Python library that allows us to connect to Microsoft SQL Server databases.

In [1]:
%pip install sqlalchemy
%pip install pymssql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.47)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Collecting pymssql
  Downloading pymssql-2.3.13-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (34 kB)
Downloading pymssql-2.3.13-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 19.7 MB/s eta 0:00:00
Installing collected packages: pymssql
Successfully installed pymssql-2.3.13

Continue with a couple imports &mdash; execute the code cell below.

In [2]:
import pandas as pd
from sqlalchemy import create_engine, inspect

You will be working with a SQL Server database hosted on Microsoft Azure. The database is named `free-sql-db-2522395` and it contains a table named `dbo.coffee_sales` with sales data for a fictional coffee company.

Execute the code cell below. It contains an expression that creates a sqlalchemy engine object by connecting to the `free-sql-db-2522395` database, and assigns that object to variable `engine`.

In [34]:
server = "cullowhee.database.windows.net"
db = "free-sql-db-2522395"
user = "Cullowheeadmin"
pwd = "8*SaqZ#U"

engine = create_engine(f"mssql+pymssql://{user}:{pwd}@{server}:1433/{db}")

Similar to exercise 3.11, pass the engine object to the `inspect` function to create an inspector object. Then, use the `get_table_names` method to retrieve the table name. Since the database contains only one table, assign the result to the variable `table` and print it.

In [35]:
inspector = inspect(engine)
tables = inspector.get_table_names()
tables

['coffee_sales']

Run the code cell below to evaluate and extract the table from the database. Inspect the resulting DataFrame to understand its structure and contents; take note of the column names.

In [36]:
df = pd.read_sql_query("SELECT * FROM coffee_sales", engine)
print(df.shape)
df.head()

(500, 6)

   id   Region Category    Sales  Profit   OrderDate
0   1  Central   Coffee  18185.0   -61.0  2023-04-13
1   2     West      Tea  19425.0  -475.0  2023-12-15
2   3     East      Tea  18935.0  5477.0  2023-09-28
3   4    South      Tea   9133.0  -999.0  2023-04-17
4   5    South   Coffee  11872.0  -626.0  2023-03-13

---

# Part 1: Show the Region, Category, Profit, and OrderDate for all sales with Profit greater than $5,900, sorted from highest to lowest Profit.

In [62]:
df = pd.read_sql_query(
    "SELECT Region, Category, Profit, OrderDate FROM coffee_sales Where Profit > 5900 Order by Profit DESC", engine)

print(df.shape)
print("Part1: Show the Region, Category, Profit, and OrderDate for all sales with profit greater than $5900, sorted from highest to lowest profit.")
df

(7, 4)
Part1: Show the Region, Category, Profit, and OrderDate for all sales with profit greater than $5900, sorted from highest to lowest profit.

    Region Category  Profit   OrderDate
0  Central      Tea  5980.0  2023-01-21
1     East   Coffee  5980.0  2023-10-28
2     West   Coffee  5971.0  2023-02-23
3     East   Coffee  5944.0  2023-08-31
4    South   Coffee  5936.0  2023-12-12
5    South   Coffee  5924.0  2023-08-13
6     West      Tea  5904.0  2023-11-21

# Part 2: Show the Top 10 Sales in the East region only (sorted highest first).

In [70]:
df_p2 = pd.read_sql_query("SELECT * FROM coffee_sales WHERE Region = 'East' ORDER BY Sales DESC", engine)

print("Part2: Show the Top 10 Sales in the East region only (sorted highest first.")
print(df_p2.shape)
df_p2.head(10)

Part2: Show the Top 10 Sales in the East region only (sorted highest first.
(151, 6)

    id Region  Category    Sales  Profit   OrderDate
0  106   East  Espresso  19926.0  -875.0  2023-10-16
1  497   East    Coffee  19842.0  1496.0  2023-01-04
2  365   East  Espresso  19830.0  -351.0  2023-05-31
3  237   East    Coffee  19629.0  3399.0  2023-07-06
4  243   East       Tea  19267.0  -958.0  2023-12-12
5   67   East    Coffee  19206.0  1352.0  2023-09-17
6  183   East       Tea  19149.0  2173.0  2023-05-17
7   15   East       Tea  18958.0   646.0  2023-06-01
8    3   East       Tea  18935.0  5477.0  2023-09-28
9  372   East    Coffee  18759.0  -231.0  2023-06-25

# Part 3: Show the Top 10 records with Sales greater than $8,000 and Profit greater than $2,000, sorted so the highest Sales appear first.

In [71]:
df_p3 = pd.read_sql_query("SELECT * FROM coffee_sales WHERE Sales > 8000 AND Profit > 2000 ORDER BY Sales DESC", engine)

print(df_p3.shape)
df_p3

(189, 6)

      id   Region  Category    Sales  Profit   OrderDate
0    343  Central  Espresso  19940.0  2683.0  2023-04-05
1    327    South  Espresso  19780.0  4079.0  2023-02-04
2     31  Central       Tea  19750.0  3356.0  2023-02-28
3    299    South    Coffee  19636.0  5302.0  2023-03-09
4    237     East    Coffee  19629.0  3399.0  2023-07-06
..   ...      ...       ...      ...     ...         ...
184  308  Central    Coffee   8313.0  2957.0  2023-01-22
185   39     East  Espresso   8215.0  5430.0  2023-02-24
186   51    South       Tea   8117.0  2432.0  2023-01-14
187  121     East    Coffee   8064.0  3403.0  2023-06-21
188  260  Central       Tea   8061.0  5542.0  2023-05-24

[189 rows x 6 columns]

# Part 4: Show the ID, Sales, and Order Date where Sales are below $1,000, sorted by Sales from lowest to highest.

In [72]:
df_p4 = pd.read_sql_query("SELECT id, Sales, OrderDate FROM coffee_sales WHERE Sales < 1000 ORDER BY Sales ASC", engine)

print(df_p4.shape)
df_p4

(14, 3)

     id  Sales   OrderDate
0    58  560.0  2023-09-21
1   411  589.0  2023-04-11
2   416  605.0  2023-01-05
3   154  645.0  2023-11-23
4    50  653.0  2023-11-12
5   432  707.0  2023-05-25
6   388  713.0  2023-05-23
7   141  771.0  2023-08-19
8   268  794.0  2023-02-06
9    76  838.0  2023-10-31
10  469  852.0  2023-08-08
11  248  862.0  2023-11-04
12  430  958.0  2023-06-07
13   48  981.0  2023-10-01

# Part 5: Show all records from the first quarter of 2023 (January 1, 2023 to March 31, 2023), sorted by Order Date from earliest to latest.

In [73]:
df_p5 = pd.read_sql_query(
    "SELECT * FROM coffee_sales WHERE OrderDate >= '2023-01-01' AND OrderDate <= '2023-03-31' ORDER BY OrderDate ASC", engine)

print(df_p5.shape)
df_p5.head(10)

(101, 6)

    id   Region  Category    Sales  Profit   OrderDate
0  447     West    Coffee  14112.0  -793.0  2023-01-01
1   64    South       Tea   1752.0  1734.0  2023-01-02
2  207     West       Tea  12373.0  1875.0  2023-01-02
3  264  Central    Coffee  10266.0  3146.0  2023-01-02
4  326     West  Espresso  12222.0  -991.0  2023-01-04
5  497     East    Coffee  19842.0  1496.0  2023-01-04
6  416    South       Tea    605.0  3255.0  2023-01-05
7  129    South  Espresso   4846.0  -872.0  2023-01-05
8  335     West    Coffee   6126.0    72.0  2023-01-06
9  270     West    Coffee  10382.0  3882.0  2023-01-09